import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// These styles apply to every route in the application
import "./globals.css";

const mainFontFamily = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={mainFontFamily.className}>{children}</body>
    </html>
  );
}
